Add concurrency safety
teltech/logger pull request #25
Opened 2020-09-25 18:46 UTC by macuenca

This should address https://github.com/teltech/logger/issues/24

2020-09-25 19:22 UTC, ShawnMilo requested changes
I believe this will not work as-is. The `mux` property should be a pointer.

Example:

```go
package main

import (
        "fmt"
        "sync"
)

type thing struct {
        m sync.Mutex
}

func main() {
        var t thing

        attempt(t)
        attempt(t)
        fmt.Println("done")
}

func attempt(t thing) {
        fmt.Println("trying to get lock")
        t.m.Lock()
        fmt.Println("got lock")
}
```

Output:

```
trying to get lock
got lock
trying to get lock
got lock
done
```

2020-09-28 07:44 UTC, mlesar reviewed
@macuenca you can do what @ShawnMilo said or just fix some of the functions that are currently not pointers and then you do not have to use `mux` as a pointer:
```
func (l Log) Debug(message string) {
        ^
func (l Log) Debugf(message string, args ...interface{}) {
        ^
func (l Log) Info(message string) {
        ^
func (l Log) Infof(message string, args ...interface{}) {
        ^
func (l Log) Warn(message string) {
        ^
func (l Log) Warnf(message string, args ...interface{}) {
        ^
func (l Log) Error(message string) {
        ^
func (l Log) Errorf(message string, args ...interface{}) {
        ^
func (l Log) Fatal(message string) {
        ^
func (l Log) Fatalf(message string, args ...interface{}) {
        ^
func (l Log) error(severity, message string) {
        ^
```

Other functions are already written as pointers but these from above are not.

You can check this locally by running `go vet` or `golangci-lint run`([link](https://github.com/golangci/golangci-lint))

2020-10-07 18:45 UTC, macuenca commented
Thank you, @ShawnMilo and @mlesar !

2020-10-08 06:47 UTC, mlesar approved these changes

2020-10-09 17:14 UTC, merged